// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Model.Enum;
using System;
using System.Collections.Generic;

namespace Model.Models;

public partial class Role
{
    public AccountRoles Id { get; set; }

    public string RoleName { get; set; }

    public virtual ICollection<SystemUserAccount> SystemUserAccounts { get; set; } = new List<SystemUserAccount>();
}