// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Model.Data;

public partial class SystemUserAccount
{
    [Key]
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Username { get; set; }

    public string PhoneNumber { get; set; }

    public int? RoleId { get; set; }

    public DateTime? Birthday { get; set; }

    public string Address { get; set; }

    public DateTime? CreatedDate { get; set; }

    public bool? IsActive { get; set; }

    public virtual Role Role { get; set; }
}