// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Model.Enum;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Model.Models;

public class SystemUserAccount
{
    [Key]
    public string AccountId { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public string Username { get; set; }

    public string? Gender { get; set; }

    public string PhoneNumber { get; set; }

    public string? Avatar { get; set; }

    public AccountRoles RoleId { get; set; }

    public DateTime Birthday { get; set; }

    public string? Address { get; set; }

    public DateTime CreatedDate { get; set; } = DateTime.UtcNow;

    public AccountStatus IsActive { get; set; } = AccountStatus.Active;

    public string Token { get; set; }

    public DateTime TokenExpires { get; set; }

    public string RefreshToken { get; set; }

    public DateTime RefreshTokenExpires { get; set; }

    public bool IsEmailVerified { get; set; } = false;

    public string EmailVerificationToken { get; set; }

    public DateTime? EmailVerificationTokenExpires { get; set; }

    public virtual Role Role { get; set; }
    public virtual ICollection<Products> Products { get; set; } = new List<Products>();
}