// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Model.Data;
using Model.Models;
using System;
using System.Collections.Generic;

namespace Model.Data;

public partial class PracticeSkillContext : DbContext
{
    public PracticeSkillContext(DbContextOptions<PracticeSkillContext> options) : base(options){}

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Role__3214EC07383340E5");

            entity.ToTable("Role");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__SystemUs__3214EC079E2489F6");

            entity.ToTable("SystemUserAccount");

            entity.Property(e => e.Address).HasMaxLength(255);
            entity.Property(e => e.Birthday).HasColumnType("date");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.PhoneNumber).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);

            entity.HasOne(d => d.Role).WithMany(p => p.SystemUserAccounts)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__SystemUse__RoleI__4BAC3F29");

            entity.Property(e => e.Token)
                .HasMaxLength(500); // nếu cần giới hạn chiều dài

            entity.Property(e => e.TokenExpires)
                .HasColumnType("datetime");

            entity.Property(e => e.RefreshToken)
                .HasMaxLength(500);

            entity.Property(e => e.RefreshTokenExpires)
                .HasColumnType("datetime");

            entity.Property(e => e.IsEmailVerified)
                .HasDefaultValue(false);

            entity.Property(e => e.EmailVerificationToken)
                .HasMaxLength(500);

            entity.Property(e => e.EmailVerificationTokenExpires)
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}